[package]
name = "log_regression"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[features]
z8z-ks=[]
z16z-ks=[]


[dependencies]
